### PR TITLE
Added my name

### PR DESCRIPTION
**Pull request by Snehasis5**

### CODE REVIEW

**Comment by Snehasis5** [comment]
Added my project

**Comment by TeeWrath** [comment]
@Snehasis5 I see that you have just changed your name. We appreciate your efforts to take the first steps into your open source journey. However, a portfolio is a website where you describe yourself, your skills, projects, links to your social handles and another details. I recommend that you make a vivid and descriptive portfolio. You can continue to add commits to your forked repository.

**Comment by Snehasis5** [comment]
Added an updated version

**Comment by Snehasis5** [comment]
updated

**Pull request closed without merging**
